export const carouselData = [
    {
      id: 1,
      name: "Guardians Of The Galaxy Vol.3",
      rating: 9.7,
      time: "2hr : 32mins",
      desc: "Cho dù vũ trụ này có bao la đến đâu, các Vệ Binh của chúng ta cũng không thể trốn chạy mãi mãi. Vệ Binh Dải Ngân Hà 3 dự kiến khởi chiếu tại rạp từ 03.05.2023",
      starring: "Chris Pratt, Zoe Saldana, Dave Bautista",
      genres: "Action",
      tags: "Hành Động, Phiêu Lưu, Thần thoại",
      cover: "../images/banner1.jpg",
      trailer: "",
      date: "03-May-2023",
    },
    {
      id: 2,
      name: "John Wick 4",
      rating: 9.6,
      time: "2hr : 22mins",
      desc: "John Wick: Chapter 4 là câu chuyện của John Wick (Keanu Reeves) đã khám phá ra con đường để đánh bại High Table. Nhưng trước khi có thể kiếm được tự do, Wick phải đối đầu với kẻ thù mới với những liên minh hùng mạnh trên toàn cầu và những lực lượng biến những người bạn cũ thành kẻ thù",
      starring: "Keanu Reeves, Scott Adkins",
      genres: "Adventures",
      tags: "Hành Động,Phiêu Lưu",
      cover: "../images/banner2.jpg",
      trailer: "",
      date: "10-JUL-2023",
    },
    {
      id: 3,
      name: "Scream 6",
      rating: 6.8,
      time: "2hr : 22mins",
      desc: "Scream VI là một bộ phim về kẻ giết người của Mỹ năm 2023 do Matt Bettinelli-Olpin và Tyler Gillett đạo diễn, James Vanderbilt và Guy Busick viết kịch bản. Đây là phần tiếp theo của Scream và là phần thứ sáu trong loạt phim Scream",
      starring: "Jenna Ortega, Melissa Barrera",
      genres: "Kinh dị",
      tags: "Kinh dị,Phim chặt chém ",
      cover: "../images/banner3.jpg",
      trailer: "",
      date: "20-FEB-2023",
    },
    {
      id: 4,
      name: "Super Mario Bros",
      rating: 8.9,
      time: "2hr : 22mins",
      desc: "Phim anh em Super Mario là một bộ phim điện ảnh hoạt hình máy tính thuộc thể loại kỳ ảo hành động giả tưởng công chiếu năm 2023 dựa trên thương hiệu trò chơi điện tử nổi tiếng Mario của Nintendo",
      starring: "Anya Taylor, Jack Black",
      genres: "Hoạt hình",
      tags: "Hoạt hình, Hài, Phiêu lưu",
      cover: "../images/banner4.jpg",
      trailer: "",
      date: "12-Aug-2023",
    },
  ]